CC = gcc
CFLAGS = -Wall -Wextra -std=c99

fastio:
	$(CC) $(CFLAGS) -DFASTIO ex13q1.c -o fastio

easyio:
	$(CC) $(CFLAGS) ex13q1.c -o easyio

clean:
	rm -f fastio easyio output_3 student_3 args_3 input_3